### ISSUE TITLE
Does actor support multiple feature files?

### ISSUE THREAD

**Issue by LayMui** [serenity-js/serenity-js-cucumber-webdriverio-template#12]
When I add a new feature and add the implementation step definition, it show error
☕ImplementationPendingError: Step implementation missing:
[test:execute] [0-1]     
[test:execute] [0-1]     Given('{actor} is at the embassy', function (actor) {
[test:execute] [0-1]       // Write code here that turns the phrase above into concrete actions
[test:execute] [0-1]       return 'pending';
[test:execute] [0-1]     });

here is my feature file
Background: 
      Given John is at the embassy

    Scenario: Fill up registration form
    When he fill up his registration details
    | username | age | residency | accounts | nationality |
    | johnmark | 48  | resident  | Savings  | USA         |
    Then he is able to submit his form

here is step definition:
Given('{actor} is at the embassy', async (actor: Actor) =>
    actor.attemptsTo(
        Navigate.to('https://form-validation-aleph-tav.vercel.app/')
    )
);

**Comment by jan-molak** [comment]
Hey @LayMui! 

So it looks like Cucumber couldn't match this step:
```gherkin
Background:
 
  Given John is at the embassy
```
With this step definition:
```typescript
Given('{actor} is at the embassy', async (actor: Actor) =>
  actor.attemptsTo(
    Navigate.to('https://form-validation-aleph-tav.vercel.app/')
  ))
```

Since both the step and the step definition look fine at the first glance, I'd suggest to check if the parameter type translating `{actor}` is registered in your test suite. Have a look at [this example](https://github.com/serenity-js/serenity-js-cucumber-webdriverio-template/blob/3af88bcf19a5df0b2f00107f408ed54393e5bd59/features/support/parameters.ts#L4-L10).

Hope this helps!
